### ISSUE TITLE
<module:Document>': uninitialized constant Mongoid::Document (NameError)

### ISSUE THREAD

**Issue by cenbek** [frodsan/mongoid-minitest#18]
I add mongoid-minitest gem, and bundle the Gemfile. I add requirements to minitest_helper.rb file.  When I run my tests, it gives me "<module:Document>': uninitialized constant Mongoid::Document (NameError)" error.

**Comment by rmm5t** [comment]
Working towards Minitest 5 and (more importantly) true Mongoid 4 should fix this issue. Closing this in favor of #19 and #20.

**Comment by alChaCC** [comment]
Hi, I updated  mongoid to 5.0.0.beta, still have this issue.
My Gemfile:
```
...
group :development, :test do
  gem "minitest"
  gem "minitest-rails"
  gem "minitest-rails-capybara"
  gem 'simplecov', :require => false 
  gem "minitest-reporters" 
  gem "minitest-stub_any_instance"

  gem "minitest-bang" 
  gem "minitest-line"

  gem "factory_girl" 
  gem "factory_girl_rails", "~> 4.0"
  gem "mocha", :require => false
  gem 'mongoid-minitest'
  gem "minitest-matchers_vaccine"
end
... 
```
here is my Gemfile.lock
```
GEM
  remote: https://rubygems.org/
  specs:
    actionmailer (4.1.6)
      actionpack (= 4.1.6)
      actionview (= 4.1.6)
      mail (~> 2.5, >= 2.5.4)
    actionpack (4.1.6)
      actionview (= 4.1.6)
      activesupport (= 4.1.6)
      rack (~> 1.5.2)
      rack-test (~> 0.6.2)
    actionview (4.1.6)
      activesupport (= 4.1.6)
      builder (~> 3.1)
      erubis (~> 2.7.0)
    activemodel (4.1.6)
      activesupport (= 4.1.6)
      builder (~> 3.1)
    activerecord (4.1.6)
      activemodel (= 4.1.6)
      activesupport (= 4.1.6)
      arel (~> 5.0.0)
    activesupport (4.1.6)
      i18n (~> 0.6, >= 0.6.9)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.1)
      tzinfo (~> 1.1)
    ansi (1.5.0)
    arel (5.0.1.20140414130214)
    bson (3.2.1)
    bson_ext (1.5.1)
    builder (3.2.2)
    capistrano (3.4.0)
      i18n
      rake (>= 10.0.0)
      sshkit (~> 1.3)
    capistrano-bundler (1.1.4)
      capistrano (~> 3.1)
      sshkit (~> 1.2)
    capistrano-passenger (0.1.1)
      capistrano (~> 3.0)
    capistrano-precompile-on-local (0.0.2)
      capistrano (>= 3.0)
      capistrano-rails
    capistrano-rails (1.1.3)
      capistrano (~> 3.1)
      capistrano-bundler (~> 1.1)
    capistrano-rvm (0.1.2)
      capistrano (~> 3.0)
      sshkit (~> 1.2)
    capybara (2.4.4)
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    chronic (0.10.2)
    coderay (1.1.0)
    coffee-rails (4.0.1)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.9.1.1)
    colorize (0.7.7)
    connection_ninja (0.4.1)
    daemons (1.2.3)
    docile (1.1.5)
    erubis (2.7.0)
    ethon (0.7.4)
      ffi (>= 1.3.0)
    eventmachine (1.0.7)
    execjs (2.5.2)
    factory_girl (4.5.0)
      activesupport (>= 3.0.0)
    factory_girl_rails (4.5.0)
      factory_girl (~> 4.5.0)
      railties (>= 3.0.0)
    ffi (1.9.10)
    geocoder (1.2.9)
    hike (1.2.3)
    i18n (0.7.0)
    jbuilder (2.3.1)
      activesupport (>= 3.0.0, < 5)
      multi_json (~> 1.2)
    jquery-rails (3.1.3)
      railties (>= 3.0, < 5.0)
      thor (>= 0.14, < 2.0)
    json (1.8.3)
    jwt (1.5.1)
    mail (2.6.3)
      mime-types (>= 1.16, < 3)
    metaclass (0.0.4)
    method_source (0.8.2)
    mime-types (2.6.1)
    mini_portile (0.6.2)
    minitest (5.8.0)
    minitest-activemodel (1.1.0)
      activemodel (>= 3.2)
      minitest (~> 5.0)
    minitest-bang (1.0.4)
      minitest (>= 4.7.5)
    minitest-capybara (0.7.2)
      capybara (~> 2.2)
      minitest (~> 5.0)
      rake
    minitest-line (0.6.3)
      minitest (~> 5.0)
    minitest-matchers_vaccine (1.0.3)
      minitest (~> 5.0)
    minitest-metadata (0.5.3)
      minitest (>= 4.7, < 6.0)
    minitest-rails (2.2.0)
      minitest (~> 5.7)
      railties (~> 4.1)
    minitest-rails-capybara (2.1.1)
      capybara (~> 2.0)
      minitest-capybara (~> 0.7.0)
      minitest-metadata (~> 0.5.0)
      minitest-rails (~> 2.1)
    minitest-reporters (1.0.19)
      ansi
      builder
      minitest (>= 5.0)
      ruby-progressbar
    minitest-stub_any_instance (1.0.1)
    mocha (1.1.0)
      metaclass (~> 0.0.1)
    mongo (2.1.0.beta)
      bson (~> 3.0)
    mongoid (5.0.0.beta)
      activemodel (~> 4.0)
      mongo (= 2.1.0.beta)
      origin (~> 2.1)
      tzinfo (>= 0.3.37)
    mongoid-minitest (1.1.0)
      minitest (~> 5.0)
      minitest-activemodel (~> 1.1)
      mongoid (>= 3)
    multi_json (1.11.0)
    mysql2 (0.3.18)
    net-scp (1.2.1)
      net-ssh (>= 2.6.5)
    net-ssh (2.9.2)
    nokogiri (1.6.6.2)
      mini_portile (~> 0.6.0)
    origin (2.1.1)
    pry (0.10.1)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    pry-rails (0.3.4)
      pry (>= 0.9.10)
    pry-remote (0.1.8)
      pry (~> 0.9)
      slop (~> 3.0)
    rack (1.5.5)
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (4.1.6)
      actionmailer (= 4.1.6)
      actionpack (= 4.1.6)
      actionview (= 4.1.6)
      activemodel (= 4.1.6)
      activerecord (= 4.1.6)
      activesupport (= 4.1.6)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.1.6)
      sprockets-rails (~> 2.0)
    railties (4.1.6)
      actionpack (= 4.1.6)
      activesupport (= 4.1.6)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (10.4.2)
    rdoc (4.2.0)
      json (~> 1.4)
    ruby-progressbar (1.7.5)
    sass (3.2.19)
    sass-rails (4.0.5)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.2.2)
      sprockets (~> 2.8, < 3.0)
      sprockets-rails (~> 2.0)
    sdoc (0.4.1)
      json (~> 1.7, >= 1.7.7)
      rdoc (~> 4.0)
    settingslogic (2.0.9)
    simplecov (0.10.0)
      docile (~> 1.1.0)
      json (~> 1.8)
      simplecov-html (~> 0.10.0)
    simplecov-html (0.10.0)
    slop (3.6.0)
    spring (1.3.6)
    sprockets (2.12.4)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    sprockets-rails (2.3.2)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      sprockets (>= 2.8, < 4.0)
    sshkit (1.7.1)
      colorize (>= 0.7.0)
      net-scp (>= 1.1.2)
      net-ssh (>= 2.8.0)
    thin (1.6.3)
      daemons (~> 1.0, >= 1.0.9)
      eventmachine (~> 1.0)
      rack (~> 1.0)
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (1.4.1)
    turbolinks (2.5.3)
      coffee-rails
    typhoeus (0.7.2)
      ethon (>= 0.7.4)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (2.7.1)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    versionist (1.4.1)
      activesupport (>= 3)
      railties (>= 3)
      yard (~> 0.7)
    whenever (0.9.4)
      chronic (>= 0.6.3)
    will_paginate (3.0.7)
    xpath (2.0.0)
      nokogiri (~> 1.3)
    yard (0.8.7.6)

PLATFORMS
  ruby

DEPENDENCIES
  bson_ext
  capistrano
  capistrano-passenger
  capistrano-precompile-on-local
  capistrano-rails
  capistrano-rvm
  coffee-rails (~> 4.0.0)
  connection_ninja
  factory_girl
  factory_girl_rails (~> 4.0)
  geocoder
  jbuilder (~> 2.0)
  jquery-rails
  jwt
  minitest
  minitest-bang
  minitest-line
  minitest-matchers_vaccine
  minitest-rails
  minitest-rails-capybara
  minitest-reporters
  minitest-stub_any_instance
  mocha
  mongoid (~> 5.0.0.beta)
  mongoid-minitest
  mysql2
  pry
  pry-rails
  pry-remote
  rails (= 4.1.6)
  sass-rails (~> 4.0.3)
  sdoc (~> 0.4.0)
  settingslogic
  simplecov
  spring
  thin
  turbolinks
  typhoeus
  uglifier (>= 1.3.0)
  versionist
  whenever
  will_paginate (~> 3.0.6)

```
